// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.https://erfeweapxscwghzlympz.supabase.co;
const SUPABASE_PUBLISHABLE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZmV3ZWFweHNjd2doemx5bXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTA3OTcsImV4cCI6MjA3NjM4Njc5N30.zdolukn_PHiqT0CF_JBWr-GHI2ZKqAEPadSBFRCF7bM;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
